name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: enricay/github-actions-templates/.github/workflows/deploy-template.yml@main
    with:
      environment: "production"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
